# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions


class TokenStatus_Active(pydantic.BaseModel):
    type: typing_extensions.Literal["active"]

    class Config:
        frozen = True


class TokenStatus_Expired(pydantic.BaseModel):
    type: typing_extensions.Literal["expired"]

    class Config:
        frozen = True


class TokenStatus_Revoked(pydantic.BaseModel):
    type: typing_extensions.Literal["revoked"]

    class Config:
        frozen = True


TokenStatus = typing_extensions.Annotated[
    typing.Union[TokenStatus_Active, TokenStatus_Expired, TokenStatus_Revoked], pydantic.Field(discriminator="type")
]
