# This file was auto-generated by Fern from our API Definition.

from backports.cached_property import cached_property

from .resources.owner.client import OwnerClient
from .resources.token.client import TokenClient


class FernNursery:
    def __init__(self, *, environment: str):
        self._environment = environment

    @cached_property
    def token(self) -> TokenClient:
        return TokenClient(environment=self._environment)

    @cached_property
    def owner(self) -> OwnerClient:
        return OwnerClient(environment=self._environment)
